/**
 * endings_data.js — 6 endings: Imanje Prezimlelo, Dobra Sezona, Dovoljno,
 * Zima bez Rezervi, Trula Berba, Medenjaci.
 */

/** @type {Array<{id: string, title: string, subtitle: string, icon: string, description: string, aforizam: string, score_mult: number}>} */
export const ENDINGS_DATA = [
  {
    id: 'imanje_prezimlelo',
    title: 'Imanje Prezimlelo',
    subtitle: 'Savršena sezona',
    icon: '🏡',
    description: 'Podrum je pun. Bačva kiselog kupusa stoji. Rakija peva. Sve što je trebalo — urađeno je.',
    aforizam: 'Ono što ruka ubere, pamet sačuva. Zima ne pita — odgovor si ti dao u jesen.',
    score_mult: 1.0,
    min_score: 90,
    brand_tag: 'guncati',
  },
  {
    id: 'dobra_sezona',
    title: 'Dobra Sezona',
    subtitle: 'Solidna zima',
    icon: '🌾',
    description: 'Nisi sve stigao, ali kesa je puna. Tegle čekaju januar. Može i bolje — ali može i mnogo gore.',
    aforizam: 'Berba nije samo sakupljanje. Berba je odluka: šta danas, šta čuvaš za sutra.',
    score_mult: 0.85,
    min_score: 65,
    brand_tag: 'guncati',
  },
  {
    id: 'dovoljno',
    title: 'Dovoljno',
    subtitle: 'Prezimićeš',
    icon: '🥬',
    description: 'Nije puno, ali je dovoljno. Zima je duga — ali ne beskrajna. Imaš šta da staviš na sto.',
    aforizam: '"Dovoljno" je reč koja sazri kasno. Prezimiš, i ona postaje zahvalnost.',
    score_mult: 0.70,
    min_score: 45,
    brand_tag: null,
  },
  {
    id: 'zima_bez_rezervi',
    title: 'Zima bez Rezervi',
    subtitle: 'Biće teška',
    icon: '❄️',
    description: 'Berba je bila tu. Sirovine su propale. Vreme je potrošeno na krive stvari. Januar dolazi prazan.',
    aforizam: 'Svaka propala paprika je propuštena odluka. Sledeće jesen — ne čekaj.',
    score_mult: 0.50,
    min_score: 0,
    brand_tag: null,
  },
  {
    id: 'trula_berba',
    title: 'Trula Berba',
    subtitle: 'Propušten momenat',
    icon: '🍂',
    description: 'Bačva nije pokrenuta. Sirovine su istrulile. Sve je stajalo — a trebalo je raditi. Jesen ne čeka.',
    aforizam: 'Bačva propuštena jednom je greška. Bačva propuštena svaki put — to je karakter.',
    score_mult: 0.30,
    min_score: 0,
    brand_tag: null,
    requires_bacva_failed: true,
  },
  {
    id: 'medenjaci',
    title: 'Medenjaci',
    subtitle: 'Masterclass završen',
    icon: '🍪',
    description: 'Nisi samo napunio podrum — napravio si brand artikl. Guncati medenjaci sa džemom. MKDSLend na stolu.',
    aforizam: 'Tradicija nije muzej. Tradicija je kuhinja koja miriše danas.',
    score_mult: 1.15,
    min_score: 0,
    brand_tag: 'mkdslend',
    prestige_only: true,
  },
];
