/**
 * recipes_data.js — Recipe tabela: ajvar, pelat, turšija, kiseli kupus, sušeno voće,
 * džem, pekmez, sušene šljive, medenjaci, rakija.
 */

import { YIELD } from '../config.js';

/** @type {import('../entities/recipe.js').Recipe[]} */
export const RECIPES_DATA = [
  {
    id: 'ajvar',
    label: 'Ajvar',
    icon: '🫙',
    inputs: { paprike: 10 },
    output: 'ajvar',
    yield_rate: YIELD.ajvar,
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Guncati Masterclass: Pravi ajvar traži minimum 10 kg paprike na jednu seriju.',
  },
  {
    id: 'sos',
    label: 'Sos od paradajza',
    icon: '🍅',
    inputs: { paradajz: 8 },
    output: 'sos',
    yield_rate: YIELD.sos,
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'MKDSLend: Domaći sos od paradajza — bez konzervansa, bez kompromisa.',
  },
  {
    id: 'pelat',
    label: 'Pelat',
    icon: '🥫',
    inputs: { paradajz: 10 },
    output: 'pelat',
    yield_rate: YIELD.pelat,
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Pelat: Blanširan paradajz bez kore. Osnova zimske kuhinje.',
  },
  {
    id: 'dzem',
    label: 'Džem od jabuka',
    icon: '🍓',
    inputs: { jabuke: 8 },
    output: 'dzem',
    yield_rate: YIELD.dzem,
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Guncati: Jabuka sa imanja — džem bez industrijskog šećera.',
  },
  {
    id: 'pekmez',
    label: 'Pekmez od šljiva',
    icon: '🫐',
    inputs: { sljive: 8 },
    output: 'pekmez',
    yield_rate: YIELD.pekmez,
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Pekmez od šljive: Kuvanje na tihoj vatri, mešanje 2-3 sata. Guncati domaća tradicija.',
  },
  {
    id: 'tursija',
    label: 'Turšija (pasivna)',
    icon: '🥒',
    inputs: { krastavci: 5, paprike: 3 },
    output: 'tursija',
    yield_rate: YIELD.tursija,
    slot_cost: 1,
    passive_days: 3,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Turšija: Fermentacija 3 dana. Krastavci + paprike + bostanuša u salamuri.',
  },
  {
    id: 'kiseli_kupus',
    label: 'Kiseli kupus (bačva)',
    icon: '🥬',
    inputs: { kupus: 20 },
    output: 'kiseli_kupus',
    yield_rate: 0.85,
    slot_cost: 2, // Handled by barrel_init.js
    passive_days: 7,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Bačva kiselog kupusa: Inicijacija u prvim danima berbe — ne može čekati!',
  },
  {
    id: 'suseno_voce',
    label: 'Sušeno voće',
    icon: '🍎',
    inputs: { jabuke: 5 },
    output: 'suseno_voce',
    yield_rate: YIELD.suseno,
    slot_cost: 1,
    passive_days: 2,
    unlock_day: null,
    prestige_only: false,
    masterclass: 'Sušeno voće: Samo sunčani dani pogodni za sušenje na vazduhu.',
  },
  {
    id: 'sušene_šljive',
    label: 'Sušene šljive',
    icon: '🫐',
    inputs: { sljive: 5 },
    output: 'sušene_šljive',
    yield_rate: 0.35,
    slot_cost: 1,
    passive_days: 2,
    unlock_day: 5,
    prestige_only: false,
    masterclass: 'Sušene šljive: Guncati specijalitet. Dostupno od Dana 5.',
  },
  {
    id: 'rakija',
    label: 'Rakija (destilacija)',
    icon: '🫗',
    inputs: { jabuke: 20, sljive: 10 },
    output: 'rakija',
    yield_rate: YIELD.rakija,
    slot_cost: 2,
    passive_days: null,
    unlock_day: 7, // Handled by rakija entity
    prestige_only: false,
    masterclass: 'Rakija: Domaća destilacija do 50L godišnje. Guncati — pravi spiritus loci.',
  },
  {
    id: 'medenjaci',
    label: 'Medenjaci (prestige)',
    icon: '🍪',
    inputs: { dzem: 2 },
    output: 'medenjaci',
    yield_rate: 3.5, // kg medenjaka iz kg džema
    slot_cost: 1,
    passive_days: null,
    unlock_day: null,
    prestige_only: true,
    masterclass: 'Medenjaci sa džemom: Run 2+ nagrada. MKDSLend brand artikl.',
  },
];
