// Full ITEMS array — shapes, colors, labels, points
export const ITEMS = [
  {
    id: 'karta',
    label: 'Karta',
    emoji: '🏟',
    shape: [[1, 1]],
    color: '#FFD700',
    required: true,
    points: 50,
  },
  {
    id: 'cup',
    label: 'Časa',
    emoji: '♻',
    shape: [[1]],
    color: '#4FC3F7',
    required: true,
    points: 30,
  },
  {
    id: 'sluskalice',
    label: 'Slušalice',
    emoji: '🎧',
    shape: [[1, 1], [1, 0]],
    color: '#BA68C8',
    required: true,
    points: 40,
  },
  {
    id: 'sunblock',
    label: 'Krema',
    emoji: '☀',
    shape: [[1], [1]],
    color: '#FFB74D',
    required: true,
    points: 20,
  },
  {
    id: 'boca',
    label: 'Boca',
    emoji: '💧',
    shape: [[1], [1], [1]],
    color: '#29B6F6',
    required: true,
    points: 35,
  },
  {
    id: 'kabel',
    label: 'Kabel',
    emoji: '🔌',
    shape: [[1, 1]],
    color: '#78909C',
    required: true,
    points: 25,
  },
  {
    id: 'jakna',
    label: 'Jakna',
    emoji: '🧥',
    shape: [[1, 1, 1], [1, 1, 1]],
    color: '#66BB6A',
    required: false,
    points: 60,
  },
  {
    id: 'powerbank',
    label: 'Powerbank',
    emoji: '🔋',
    shape: [[1, 1], [0, 1]],
    color: '#EF5350',
    required: false,
    points: 30,
  },
  {
    id: 'naocare',
    label: 'Naočare',
    emoji: '😎',
    shape: [[1, 1]],
    color: '#26C6DA',
    required: false,
    points: 20,
  },
  {
    id: 'grickalice',
    label: 'Grickalice',
    emoji: '🍫',
    shape: [[1], [1]],
    color: '#A1887F',
    required: false,
    points: 15,
  },
  {
    id: 'kes',
    label: 'Novčanik',
    emoji: '👛',
    shape: [[1, 1], [1, 0]],
    color: '#EC407A',
    required: false,
    points: 25,
  },
  {
    id: 'narukvica',
    label: 'Narukvica',
    emoji: '✨',
    shape: [[1, 1, 1]],
    color: '#FFEE58',
    required: false,
    points: 20,
  },
];

export function getItemById(id) {
  return ITEMS.find(item => item.id === id) || null;
}
