name = "avala-run-leaderboard"
main = "index.js"
compatibility_date = "2024-01-01"

# SERVER_SECRET is set via `wrangler secret put` (not in file)

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "40ca259528164815a751a3f225a462f9"
