// venues.js — all 8 venue configurations
export const VENUES = [
  {
    id: 'sumski-sat',
    name: 'Šumski Sat',
    emoji: '🌲',
    capacity: 200,
    difficulty: 1,
    difficultyStars: 1,
    neighborDist: 150,
    reflection: 4,
    windBase: 0,
    windEnabled: false,
    happinessThreshold: 60,
    budgetStart: 2000,
    terrainType: 'forest',
    bgColor: '#0d1a0d',
    zones: [
      { id: 'main', name: 'Main Stage', pos: { x: 30, y: 30 }, defaultDb: 85, isControllable: true },
      { id: 'fill', name: 'Fill Zone',  pos: { x: 50, y: 30 }, defaultDb: 75, isControllable: true }
    ],
    neighborPos: { x: 80, y: 15 }
  },
  {
    id: 'recna-obala',
    name: 'Rečna Obala',
    emoji: '🌊',
    capacity: 400,
    difficulty: 2,
    difficultyStars: 2,
    neighborDist: 200,
    reflection: 3,
    windBase: 1,
    windEnabled: true,
    happinessThreshold: 65,
    budgetStart: 3500,
    terrainType: 'river',
    bgColor: '#0d1220',
    zones: [
      { id: 'main',  name: 'Main Stage',  pos: { x: 25, y: 35 }, defaultDb: 87, isControllable: true },
      { id: 'fill',  name: 'Fill Zone',   pos: { x: 45, y: 35 }, defaultDb: 77, isControllable: true },
      { id: 'delay', name: 'Delay Tower', pos: { x: 60, y: 35 }, defaultDb: 72, isControllable: true }
    ],
    neighborPos: { x: 82, y: 20 }
  },
  {
    id: 'industrijska-zona',
    name: 'Industrijska Zona',
    emoji: '🏭',
    capacity: 800,
    difficulty: 3,
    difficultyStars: 3,
    neighborDist: 100,
    reflection: 8,
    windBase: 0,
    windEnabled: false,
    happinessThreshold: 70,
    budgetStart: 5000,
    terrainType: 'concrete',
    bgColor: '#141414',
    zones: [
      { id: 'main',    name: 'Main Stage',  pos: { x: 20, y: 30 }, defaultDb: 90, isControllable: true },
      { id: 'fill',    name: 'Fill Zone',   pos: { x: 40, y: 30 }, defaultDb: 80, isControllable: true },
      { id: 'monitor', name: 'Monitor',     pos: { x: 30, y: 42 }, defaultDb: 75, isControllable: true }
    ],
    neighborPos: { x: 70, y: 10 }
  },
  {
    id: 'urbani-blok',
    name: 'Urbani Blok',
    emoji: '🏙️',
    capacity: 600,
    difficulty: 4,
    difficultyStars: 3,
    neighborDist: 80,
    reflection: 8,
    windBase: 0,
    windEnabled: false,
    happinessThreshold: 70,
    budgetStart: 6000,
    terrainType: 'concrete',
    bgColor: '#0d0d1a',
    zones: [
      { id: 'main',    name: 'Main Stage',   pos: { x: 25, y: 32 }, defaultDb: 88, isControllable: true },
      { id: 'fill',    name: 'Fill Zone',    pos: { x: 42, y: 32 }, defaultDb: 78, isControllable: true },
      { id: 'monitor', name: 'Monitor',      pos: { x: 33, y: 45 }, defaultDb: 74, isControllable: true },
      { id: 'delay',   name: 'Delay Tower',  pos: { x: 58, y: 32 }, defaultDb: 70, isControllable: true }
    ],
    neighborPos: { x: 78, y: 15 }
  },
  {
    id: 'prigradska-arena',
    name: 'Prigradska Arena',
    emoji: '🏟️',
    capacity: 1500,
    difficulty: 5,
    difficultyStars: 4,
    neighborDist: 300,
    reflection: 2,
    windBase: 2,
    windEnabled: true,
    happinessThreshold: 72,
    budgetStart: 9000,
    terrainType: 'open',
    bgColor: '#0a0a15',
    zones: [
      { id: 'main',    name: 'Main Stage',   pos: { x: 20, y: 30 }, defaultDb: 92, isControllable: true },
      { id: 'fill',    name: 'Fill Zone A',  pos: { x: 40, y: 30 }, defaultDb: 82, isControllable: true },
      { id: 'fill2',   name: 'Fill Zone B',  pos: { x: 55, y: 30 }, defaultDb: 78, isControllable: true },
      { id: 'delay',   name: 'Delay Tower',  pos: { x: 68, y: 30 }, defaultDb: 74, isControllable: true },
      { id: 'monitor', name: 'Monitor',      pos: { x: 30, y: 44 }, defaultDb: 75, isControllable: true }
    ],
    neighborPos: { x: 88, y: 10 }
  },
  {
    id: 'recni-brod',
    name: 'Rečni Brod',
    emoji: '🚢',
    capacity: 300,
    difficulty: 5,
    difficultyStars: 4,
    neighborDist: 250,
    reflection: 3,
    windBase: 3,
    windEnabled: true,
    happinessThreshold: 68,
    budgetStart: 7500,
    terrainType: 'water',
    bgColor: '#050d1a',
    zones: [
      { id: 'main',  name: 'Main Deck',    pos: { x: 30, y: 28 }, defaultDb: 88, isControllable: true },
      { id: 'fill',  name: 'Stern Fill',   pos: { x: 48, y: 28 }, defaultDb: 78, isControllable: true },
      { id: 'delay', name: 'Bow Delay',    pos: { x: 62, y: 28 }, defaultDb: 72, isControllable: true }
    ],
    neighborPos: { x: 85, y: 15 }
  },
  {
    id: 'avala-predgorje',
    name: 'Avala Predgorje',
    emoji: '⛰️',
    capacity: 2500,
    difficulty: 7,
    difficultyStars: 5,
    neighborDist: 400,
    reflection: 6,
    windBase: 4,
    windEnabled: true,
    happinessThreshold: 75,
    budgetStart: 14000,
    terrainType: 'mountain',
    bgColor: '#0a0a12',
    zones: [
      { id: 'main',    name: 'Main Stage',    pos: { x: 18, y: 32 }, defaultDb: 95, isControllable: true },
      { id: 'fill',    name: 'Fill Zone A',   pos: { x: 35, y: 32 }, defaultDb: 85, isControllable: true },
      { id: 'fill2',   name: 'Fill Zone B',   pos: { x: 50, y: 32 }, defaultDb: 80, isControllable: true },
      { id: 'delay',   name: 'Delay Tower',   pos: { x: 63, y: 32 }, defaultDb: 76, isControllable: true },
      { id: 'monitor', name: 'Monitor',       pos: { x: 26, y: 44 }, defaultDb: 76, isControllable: true },
      { id: 'side',    name: 'Side Fill',     pos: { x: 26, y: 20 }, defaultDb: 80, isControllable: true }
    ],
    neighborPos: { x: 90, y: 8 }
  },
  {
    id: 'avala-open-air',
    name: 'Avala Open-Air',
    emoji: '🌟',
    capacity: 5000,
    difficulty: 8,
    difficultyStars: 5,
    neighborDist: 500,
    reflection: 5,
    windBase: 3,
    windEnabled: true,
    happinessThreshold: 78,
    budgetStart: 20000,
    terrainType: 'open',
    bgColor: '#05050f',
    zones: [
      { id: 'main',    name: 'Main Stage',    pos: { x: 15, y: 30 }, defaultDb: 100, isControllable: true },
      { id: 'fill',    name: 'Fill Zone A',   pos: { x: 30, y: 30 }, defaultDb: 88,  isControllable: true },
      { id: 'fill2',   name: 'Fill Zone B',   pos: { x: 45, y: 30 }, defaultDb: 84,  isControllable: true },
      { id: 'fill3',   name: 'Fill Zone C',   pos: { x: 58, y: 30 }, defaultDb: 80,  isControllable: true },
      { id: 'delay',   name: 'Delay Tower A', pos: { x: 68, y: 30 }, defaultDb: 76,  isControllable: true },
      { id: 'delay2',  name: 'Delay Tower B', pos: { x: 76, y: 30 }, defaultDb: 72,  isControllable: true },
      { id: 'monitor', name: 'Monitor',       pos: { x: 22, y: 42 }, defaultDb: 78,  isControllable: true },
      { id: 'side',    name: 'Side Fill',     pos: { x: 22, y: 18 }, defaultDb: 82,  isControllable: true }
    ],
    neighborPos: { x: 92, y: 6 }
  }
];
